name: Build Page

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
          version: 7
          run_install: false
        
    - name: build
      run: |
        ls
        cd config-front
        pnpm install
        pnpm run build

    - uses: actions/upload-artifact@master
      with:
        name: page
        path: bin/site
